theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: Mr. Abarnan Rajkhowa
description: Lecturer in Hailakandi Polytechnic/
             Computer Science Engineering/
             A reader / A learner / an educator / coder /
             "GATE CS 2020" Qualified with /500+ score
             
show_downloads: false
